language: node_js
node_js:
- "0.12"
- "4"
- "5"
- "6"
install:
- npm install
notifications:
  slack:
    on_success: change
    on_failure: always
    secure: qC9U4oI1PIURVL5zaezKb8HrhmbWij6hUoZuwSTkCWUj2ZuT15e/rpWoaQ5JHLszH7G27vXlShaH8d7wNe0nIxQkPS6mAZrg3jyqH6oRFqmSLPvNbrZ62e8AwqHRlvbpHV/9U1rAfOIWdUCMKzPBl1wmMB1YEwTE8KkzpkU0+FF1kbUwfMcK8RrhMGkVdAk/xAWykS6lO4YdaMVQcBHxsE3D37tMuscDQCGsoKHLv+hbbE24dskaaSbRD7ubRvNpFttgRxdNDQFBey+r2eDs1dkJ4kdv+8kbVuym0fiD44vedxFmlggpyfjMNNR3rDa1n/0KJ1C0LvDtllka2fhhq93kGiWOZ920NlKZAFpM4RV89z7bS7qcMivf7oPxrx2UW2lQRfoQ2JA85QU+x4SZOz47mzeIRQFPZFy+1RINARq+TZczQ/kPMVCcqgTux/rPVqp+cYdAbQR7NiS6Snj2FG+cD41txyeFAk5yaxlFLt0Oa2KbmG++0qJeZ0wqQJe57+2xprAU4e19C63FYJ68skGWAo3vQDVl8n8of6vxIkTYL7+gwh43TV6GQYmIXRvGbhENgmEhOTPz2ehgtfdJ2azt6jxnTcltqaz0DEvEYVyB1SDDaaWBuRZ08fWcEKgv50eQE5hjUHEtXLw0XGth/hY1Woo6edMp0/qVWv/H7aI=
